# Terminate All Instances
---
-   name: Remove a VM and all resources that were autocreated
    azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ iname }}-VM"
        state: absent
        remove_on_absent:
            - virtual_storage

-   name: Delete network interface
    azure_rm_networkinterface:
        resource_group: "{{ resource_group }}"
        name: "{{ iname }}-NIC"
        state: absent

-   name: Delete public ip
    azure_rm_publicipaddress:
        resource_group: "{{ resource_group }}"
        name: "{{ iname }}-ip"
        state: absent

-   name: Delete Network Security Group
    azure_rm_securitygroup:
        resource_group: "{{ resource_group }}"
        name: "{{ iname }}-sg"
        state: absent

-   name: Delete managed OS disk
    azure_rm_manageddisk:
        resource_group: "{{ resource_group }}"
        name: "{{ iname }}-VM"
        state: absent
