---
ansible_python_interpreter: "python3"

region: northeurope
resource_group: "DIDA-MOBN23-DV1673-H25-LP2"
domain_name: "mobn23.me"
admin_email: mobn23@student.bth.se

vmtags:
  StudentId: mobn23

# use the NEW key you created
pub_ssh_key_location: "/home/mobn/.ssh/azure.pub"
ansible_ssh_private_key_file: "/home/mobn/.ssh/azure"

bootstrap_user: "deploy"
server_user: deploy

microblog_port: 8000