$ANSIBLE_VAULT;1.1;AES256
37643136343263613235613563386361343033646139393331306635346139653538653430383466
3937316539663331356434373136613738326666303962650a303063656537653935396538306162
61383062393730316635666438613666343365393439383238396562646231633930343431646636
6163383230663065660a643937353066386464663232653535363233383632633761626162343536
62613262356365626266656336633162663862623966303535616463383734653837353337323061
38653230393638346233623064386263316130653164323833626234383564646638626233633337
65653466356137363433623933626561353335333864633731656235353535373935303438623863
66306131643736363537363131323637613835666364356431303662303261636365613862376638
35646262623431356532313730393632646439653263353738386438623230656265613435326431
64663432366132303861633035306561633764636235643562636439343839643136383564333938
646165356461626661333039386366373736
