---
- hosts: devops
  remote_user: "{{ bootstrap_user }}"
  gather_facts: false
  become: false
  tasks:
    - name: Wait for SSH to be ready on the VM IP
      ansible.builtin.wait_for_connection:
        delay: 5
        timeout: 300

- hosts: devops
  remote_user: "{{ bootstrap_user }}"
  gather_facts: true
  become: yes
  become_method: sudo
  roles:
    - 10-first-minutes
