# Gather facts from remote instance and set as hosts
---
-   hosts: localhost
    connection: local
    gather_facts: False
    vars:
      phase: deploy
    collections:
        - azure.azcollection
    roles:
        - gather_instances
