---
- import_playbook: provision_instances.yml

- import_playbook: gather_instances_bootstrap.yml

- import_playbook: 10-first-minutes.yml

- import_playbook: gather_instances_deploy.yml

- import_playbook: microblog_app.yml

- import_playbook: microblog_db.yml

- import_playbook: deploy_lb.yml